### ISSUE TITLE
hope add some information about Trinity

### ISSUE THREAD

**Issue by pigxo** [Awesome-Layer-2/Project#30]
I have done some information collecting work about my interest in Trinity，check it out here

Trinity is a universal off-chain scaling solution, which aims to achieve real-time payments with low transaction fees, scalability and privacy protection for mainchain assets. Trinity now have the trinity-neo (based on Neo) and trinity-eth(based on Ethereum) .

Official website: https://trinity.tech/#/ 
Medium: https://medium.com/trinity-protocol 
Twitter: https://twitter.com/TrinityProtocol 
Telegram: https://t.me/TrinityStateChannels
github: https://github.com/trinity-project

Product/document

white paper (https://trinity.tech/#/writepaper)
document(https://trinity.readthedocs.io/en/latest/en-EN/index.html)

Articles

Scaling NEO: What is Trinity?（https://www.cryptoninjas.net/2018/01/07/scaling-neo-trinity/ ）

Trinity Protocol: The Scaling Solution Of The Future?（https://www.investinblockchain.com/trinity-protocol/	）

Videos

https://www.youtube.com/watch?v=t1qhME3Myus
https://www.youtube.com/watch?v=OwCvszgstN0

**Comment by Virale** [comment]
thx , I will add those ASAP :)

**Comment by Virale** [comment]
it's done.
